# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'production'
  artifactName: 'ApplicationUI'

steps:
  - task: NodeTool@0
    displayName: 'Install Node.js'
    inputs:
      versionSpec: '16.x'

  - task: Npm@1  
    displayName: 'Install Angular CLI'  
    inputs:  
      command: custom  
      verbose: false  
      customCommand: 'install -g @angular/cli@14.2.12'

  - task: Npm@1
    displayName: 'Install npm packages'
    inputs:
      command: 'install'

  - task: Npm@1  
    displayName: 'Build Angular App'
    inputs: 
      command: custom  
      verbose: false  
      customCommand: 'run build' 

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
